name: 'package extension'

on: 
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          packages: write

        steps:
        - uses: actions/checkout@v3

        - name: Checkout Submodule
          run: git submodule update --init

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - name: Install Rust stable
          uses: dtolnay/rust-toolchain@stable

        - name: Install linux dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

        - name: Install npm dependencies
          run: npm install

        - name: Install VSCE
          run: npm install -g @vscode/vsce

        - name: Install wasm
          run: cargo install wasm-pack

        - name: Build wasm
          run: npm run build-wasm

        - name: Package extension
          run: vsce package

        - name: Public Release
          id: create_release
          uses: softprops/action-gh-release@master
          with:
            tag_name: build${{ github.run_number }}
            name: v${{ github.run_number }}
            body: Public Release
            draft: false
            prerelease: false
            files: rust*.vsix
      